### ISSUE TITLE
TallgrassFeature -> VillageConfig

### ISSUE THREAD

**Issue by JDLogic** [MinecraftForge/MCPConfig#1]
Looking through the mappings, I saw that there is class `TallgrassFeature` and class `TallGrassFeature`.  The following snippet from `net.minecraft.world.gen.feature.Feature` suggest that `TallgrassFeature` should be `VillageConfig` (or something like that).

```
public abstract class Feature<C extends IFeatureConfig>
{
    public static final ArrayList<Biome.SpawnListEntry> field_202327_e = Lists.<Biome.SpawnListEntry>newArrayList();
    public static final Structure<TallgrassFeature> field_202328_f = new VillageStructure();
    public static final Structure<MineshaftConfig> field_202329_g = new MineshaftStructure();
    public static final Structure<WoodlandMansionConfig> field_202330_h = new WoodlandMansionStructure();
...
}
```

**Comment by LexManos** [comment]
Wow.. how the hell did that happen... That shouldn't of been possible my scripts check for that type of thing..
