### ISSUE TITLE
net.minecraft.world.gen.DimensionSettings -> ChunkGeneratorSettings

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MCPConfig#106]
DimensionSettings is not actually stored in dimensions but rather is stored in chunk generators. Thus the "dimension" part of its name is misleading. Instead, since DimensionSettings holds settings for what the chunk generator should use, a better name is ChunkGeneratorSettings.

Feel free to adjust the name for something else if desired

**Comment by Cyborgmas** [comment]
Explored this a bit more, its only used in the NoiseChunkGenerator with a field of "settings" 
On https://minecraft.gamepedia.com/Custom_dimension#Generator_types the "settings" field is only for noise type and is refered to as "NoiseSettings" and leads you to https://minecraft.gamepedia.com/Custom_world_generation#Noise_settings
NoiseSettings could be a good name but its already in use
