### ISSUE TITLE
[1.16.1] [Method/Field/Param]: Suggested Renames

### ISSUE THREAD

**Issue by Lanse505** [MinecraftForge/MCPConfig#109]

**Comment by Lanse505** [comment]
Accidental enter press 😓 
will

**Comment by Lanse505** [comment]
|Class Name                                                   |Unmapped Name  |Old Mapped Name              |Mapped Name                      |Comment                                                                                                                                                                                                                                              |
|-------------------------------------------------------------|---------------|-----------------------------|---------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|AbstractBlock                                                |func_215696_m  |causesSuffocation            |shouldBlockVision                |Client side only, returns if the block overlay should be rendered if the player is inside it                                                                                                                                                         |
|AbstractBlock                                                |func_203425_a  |isIn                         |matchesBlock                     |Checks if the Block matches the provided Block parameter through a == comparison                                                                                                                                                                     |
|IGuiEventListener                                            |p_212927_1_    |xPos                         |mouseX                           |                                                                                                                                                                                                                                                     |
|net.minecraft.entity.Entity                                  |field_70128_L  |removed                      |dead                             |If the player is dead, is used in isAlive and can be set back to true with revive()                                                                                                                                                                  |
|net.minecraft.client.gui.FocusableGui                        |field_230699_a_|focused                      |listener                         |                                                                                                                                                                                                                                                     |
|net.minecraft.util.text.Style                                |func_240720_a_ |createStyleFromFormattings   |mergeWithFormatting              |Does effectively what mergeStyle does, except with TextFormatting varargs as parameter (both immutable). is also forceFormatting which works the same way but only takes 1 TextFormatting, but it's client-only - might be a good idea to rename too.|
|net.minecraft.client.gui.widget.list.AbstractList            |field_230667_a_|children                     |entries                          |The list holds the contents of the Scrolling list as Entries (also the clearEntries and replaceEntries follows this name assumption)                                                                                                                 |
|net.minecraft.block.FenceGateBlock                           |field_185539_B |AABB_COLLISION_BOX_ZAXIS     |AABB_RENDER_BOX_XAXIS            |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.block.FenceGateBlock                           |field_208068_x |TRUE_AABB_COLLISION_BOX_ZAXIS|AABB_COLLISION_BOX_ZAXIS         |relies on the above fix                                                                                                                                                                                                                              |
|net.minecraft.block.NetherPortalBlock                        |p_176548_1_    |world                        |pos                              |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.block.NetherPortalBlock                        |p_201816_0_    |world                        |pos                              |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.client.audio.SimpleSound                       |p_184372_3_    |zIn                          |yIn                              |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.client.renderer.entity.ShulkerRenderer         |field_188342_a |SHULKER_ENDERGOLEM_TEXTURE   |SHULKER_TEXTURES                 |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.block.AbstractBlock.AbstractBlockState         |func_196951_e  |getRenderShape               |getCollisionShape                |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.block.AbstractBlock.AbstractBlockState         |func_235754_c_ |getRenderShapeTrue           |getRenderShape                   |relies on the above fix                                                                                                                                                                                                                              |
|net.minecraft.entity.passive.fish.TropicalFishEntity.Type    |p_204214_0_    |size                         |type                             |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.scoreboard.Scoreboard                          |func_197899_c  |getOrCreateObjective         |getObjective                     |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.scoreboard.Scoreboard                          |func_96518_b   |getObjective                 |getObjectiveNullable             |Error in Old Mappings                                                                                                                                                                                                                                |
|net.minecraft.util.text.IFormattableTextComponent            |func_230529_a_ |append                       |appendSibling                    |                                                                                                                                                                                                                                                     |
|net.minecraft.entity.Entity                                  |func_184222_aU |isNonBoss                    |canChangeDimension               |also used for fishing bobber entity, which is kinda... fishy...                                                                                                                                                                                      |
|net.minecraft.inventory.container.CartographyContainer       |p_216993_1_    |stack                        |originalMap                      |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.ShipwreckPieces    |field_204761_a |STRUCTURE_VARIANT_A          |SIDEWAYS_VARIANT                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.EndCityPieces      |p_191090_5_    |owerwrite                    |overwrite                        |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214780_a |MSCORRIDOR                   |MINESHAFT_CORRIDOR               |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214781_b |MSCROSSING                   |MINESHAFT_CROSSING               |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214780_a |MSCORRIDOR                   |                                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214781_b |MSCROSSING                   |                                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214782_c |MSROOM                       |MINESHAFT_ROOM                   |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214783_d |MSSTAIRS                     |MINESHAFT_STAIRS                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214784_e |PCP                          |PILLAGER_OUTPOST                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214785_f |NVI                          |VILLAGE                          |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214786_g |NEBCR                        |NETHER_FORTRESS_CROSSING_3       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214787_h |NEBEF                        |NETHER_FORTRESS_END              |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214788_i |NEBS                         |NETHER_FORTRESS_STRAIGHT         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214789_j |NECCS                        |NETHER_FORTRESS_CORRIDOR_3       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214790_k |NECTB                        |NETHER_FORTRESS_CORRIDOR_4       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214791_l |NECE                         |NETHER_FORTRESS_ENTRANCE         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214792_m |NESCSC                       |NETHER_FORTRESS_CROSSING_2       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214793_n |NESCLT                       |NETHER_FORTRESS_CORRIDOR         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214794_o |NESC                         |NETHER_FORTRESS_CORRIDOR_5       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214795_p |NESCRT                       |NETHER_FORTRESS_CORRIDOR_2       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214796_q |NECSR                        |NETHER_FORTRESS_NETHER_STALK_ROOM|                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214797_r |NEMT                         |NETHER_FORTRESS_THRONE           |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214798_s |NERC                         |NETHER_FORTRESS_CROSSING         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214799_t |NESR                         |NETHER_FORTRESS_STAIRS           |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214800_u |NESTART                      |NETHER_FORTRESS_START            |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214801_v |SHCC                         |STRONGHOLD_CHEST_CORRIDOR        |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214802_w |SHFC                         |STRONGHOLD_CORRIDOR              |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214803_x |SH5C                         |STRONGHOLD_CROSSING              |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214804_y |SHLT                         |STRONGHOLD_LEFT_TURN             |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214805_z |SHLI                         |STRONGHOLD_LIBRARY               |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214754_A |SHPR                         |STRONGHOLD_PORTAL_ROOM           |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214755_B |SHPH                         |STRONGHOLD_PRISON                |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214756_C |SHRT                         |STRONGHOLD_RIGHT_TURN            |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214757_D |SHRC                         |STRONGHOLD_ROOM_CROSSING         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214758_E |SHSD                         |STRONGHOLD_STAIRS                |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214759_F |SHSTART                      |STRONGHOLD_STAIRS_2              |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214760_G |SHS                          |STRONGHOLD_STRAIGHT              |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214761_H |SHSSD                        |STRONGHOLD_STAIRS_STRAIGHT       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214762_I |TEJP                         |JUNGLE_PYRAMID_PIECE             |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214763_J |ORP                          |OCEAN_RUIN_PIECE                 |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214764_K |IGLU                         |IGLOO_PIECE                      |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214765_L |TESH                         |SWAMP_HUT_PIECE                  |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214766_M |TEDP                         |DESERT_PYRAMID_PIECE             |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214767_N |OMB                          |OCEAN_MONUMENT_BUILDING          |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214768_O |OMCR                         |OCEAN_MONUMENT_CORE_ROOM         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214769_P |OMDXR                        |OCEAN_MONUMENT_DOUBLE_X_ROOM     |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214770_Q |OMDXYR                       |OCEAN_MONUMENT_DOUBLE_XY_ROOM    |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214771_R |OMDYR                        |OCEAN_MONUMENT_DOUBLE_Y_ROOM     |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214772_S |OMDYZR                       |OCEAN_MONUMENT_DOUBLE_YZ_ROOM    |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214773_T |OMDZR                        |OCEAN_MONUMENT_DOUBLE_Z_ROOM     |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214774_U |OMENTRY                      |OCEAN_MONUMENT_ENTRY_ROOM        |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214775_V |OMPENTHOUSE                  |OCEAN_MONUMENT_PENTHOUSE         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214776_W |OMSIMPLE                     |OCEAN_MONUMENT_SIMPLE_ROOM       |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214777_X |OMSIMPLET                    |OCEAN_MONUMENT_SIMPLE_TOP_ROOM   |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214778_Y |OMWR                         |OCEAN_MONUMENT_WING_ROOM         |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214779_Z |ECP                          |END_CITY_TEMPLATE                |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214751_aa|WMP                          |WOODLAND_MANSION_TEMPLATE        |                                                                                                                                                                                                                                                     |
|net.minecraft.world.gen.feature.structure.IStructurePieceType|field_214752_ab|BTP                          |BURIED_TREASURE_PIECE            |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.SimpleSound                       |p_184372_3_    |zIn                          |y                                |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.SimpleSound                       |p_184372_5_    |zTrueIn                      |zIn                              |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.SoundSource                       |func_216430_b  |setGain                      |setVolume                        |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.Listener                          |func_216466_a  |setGain                      |setVolume                        |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.Listener                          |func_216467_a  |getGain                      |getVolume                        |                                                                                                                                                                                                                                                     |
|net.minecraft.client.audio.Listener                          |field_216471_b |gain                         |volume                           |                                                                                                                                                                                                                                                     |
|net.minecraft.client.GameConfiguration                       |field_178743_b |displayInfo                  |screenSize                       |                                                                                                                                                                                                                                                     |
|net.minecraft.client.gui.widget.Widget                       |func_230431_b_ |renderButton                 |renderWidget                     |                                                                                                                                                                                                                                                     |
|net.minecraft.client.gui.fonts.TextInputUtil                 |field_216905_f |endIndex                     |selectionEnd                     |                                                                                                                                                                                                                                                     |
|net.minecraft.client.gui.fonts.TextInputUtil                 |field_216906_g |startIndex                   |selectionStart                   |                                                                                                                                                                                                                                                     |
|net.minecraft.client.gui.fonts.TextInputUtil                 |func_216896_c  |getEndIndex                  |getSelectionEnd                  |                                                                                                                                                                                                                                                     |
|net.minecraft.client.gui.fonts.TextInputUtil                 |func_216898_d  |getStartIndex                |getSelectionStart                |                                                                                                                                                                                                                                                     |

**Comment by LexManos** [comment]
A not for others: This repo is only for class name changes.
Fields/methods/params should go to the bot, or whatever other crowd sourcing system is being used.
