### ISSUE TITLE
1.16.2 Release uses outdated version

### ISSUE THREAD

**Issue by CodingModder** [MinecraftForge/MCPConfig#115]
The 1.16.2 version (https://github.com/MinecraftForge/MCPConfig/blob/master/versions/release/1.16.2/config.json) uses an old version of forgeflower, specialsource and mergetool (in the joined api). Shouldn't the latest version use latest?

**Comment by LexManos** [comment]
If there are reasons to update, sure, but it doesn't matter right now.
FF's changes arnt really useful to us. A slightly nicer string switch is the only part that is interesting. And when I get time to rebuild all the patches it might be bumped.
SpecialSource, honestly the version we use functions, and I have no idea what the upstream changes are. However it's on my very low level TODO list to replace SpecialSource entirely. As I'd prefer a project I can build myself without lombok BSODing my machine.
MergeTool API hasn't changed, so doesn't need a update. It's just the Dist/OnlyIn annotations.

**Comment by CodingModder** [comment]
ok thx for the notice
