### ISSUE TITLE
net.minecraft.world.gen.feature.AbstractSphereReplaceConfig -> CylinderReplaceFeature

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MCPConfig#117]
```java
public class AbstractSphereReplaceConfig extends Feature<SphereReplaceConfig> {
```

This is
- A `Feature` subclass, which should be suffixed with `Feature`, not `Config`
- Not an `abstract` class, so it shouldn't be prefixed with `Abstract`
- Generates a cylinder, not a sphere. This is obvious when looking at `SphereReplaceConfig`, which has a `radius` and `ySize` parameter (height).

So to fix:
 - [ ] `net.minecraft.world.gen.feature.AbstractSphereReplaceConfig` -> `CylinderReplaceFeature`

And fixing subclasses and other related classes:
 - [ ] `net.minecraft.world.gen.feature.SphereReplaceFeature` -> `SoilDiskFeature`
   - Reasoning: this is a subclass of `AbstractSphereReplaceConfig`, which is used for the `disk_gravel`, `disk_clay` and `disk_sand` configured features. It is named akin to `IcePathFeature` which is the other subclass of this class.
 - [ ] `net.minecraft.world.gen.feature.SphereReplaceConfig` -> `CylinderReplaceConfig`
   - Reasoning: fairly obvious change given this isn't a sphere.

**Comment by TelepathicGrunt** [comment]
Well, it's not actually a cylinder. The actual shape is called an ellipsoid so replace cylinder with ellipsoid and it'll be good to go!

**Comment by TelepathicGrunt** [comment]
ignore me. i'm wrong
