### ISSUE TITLE
Misleading name for AbstractBlock#causesSuffocation

### ISSUE THREAD

**Issue by 50ap5ud5** [MinecraftForge/MCPConfig#131]
In the latest 1.16.3 mappings, 20201028-1.16.3, there is a misnamed/misaligned name for AbstractBlock#causesSuffocation.

This method doesn't cause suffocation but rather tells the client if it should render the block if the player is inside it and the block isn't rendertype invisible. (Used by getOverlayBlock in OverlayRenderer).

**Comment by gigaherz** [comment]
Please don't report method/field/param name conflicts in this repository, you should comment [on the spreadsheet](https://docs.google.com/spreadsheets/d/14knNUYjYkKkGpW9VTyjtlhaCTUsPWRJ91GLOFX2d23Q/edit?usp=sharing).
