### ISSUE TITLE
SeaPickelFeature -> SeaPickleFeature

### ISSUE THREAD

**Issue by Runemoro** [MinecraftForge/MCPConfig#19]
Obviously a typo. GlowStoneFeature should be changed to GlowstoneFeature, since the block is named "Glowstone" rather than "Glow Stone".

Also, the ChunkGeneratorType class (and also the names in the Buffet GUI) gives us names for the chunk generator classes:

    static {
        SURFACE = registerChunkGenerator("surface", ChunkGeneratorOverworld::new, Settings.SURFACE, true);
        CAVES = registerChunkGenerator("caves", ChunkGeneratorNether::new, Settings.CAVES, true);
        FLOATING_ISLANDS = registerChunkGenerator("floating_islands", ChunkGeneratorEnd::new, Settings.FLOATING_ISLANDS, true);
        DEBUG = registerChunkGenerator("debug", ChunkGeneratorDebug::new, Settings.DEBUG, false);
        FLAT = registerChunkGenerator("flat", ChunkGeneratorFlat::new, Settings.FLAT, false);
    }

 - ChunkGeneratorOverworld-> ChunkGeneratorSurface
 - ChunkGeneratorEnd -> ChunkGeneratorFloatingIslands
 - ChunkGeneratorNether -> ChunkGeneratorCaves

Until 1.12, these were used only to generate the overworld/end/nether, but they should be renamed now that they've become more flexible in 1.13.

Edit: Biome.BiomeBuilder.toString() contains names for every field in the biome builder. It seems like "rainType" is actually named "precipitation", so maybe the RainType class should be renamed to "Precipitation".

**Comment by Runemoro** [comment]
Also, GenLayer -> GenLayerBiomes:

```java
public class GenLayer {
    private final IAreaFactory<LazyArea> lazyAreaFactory;

    public GenLayer(final IAreaFactory<LazyArea> lazyAreaFactoy) {
        lazyAreaFactory = lazyAreaFactoy;
    }

    public Biome[] getBiomes(final int startX, final int startZ, final int xSize, final int zSize, @Nullable final Biome defaultBiome) {
        final LazyArea area = lazyAreaFactory.make(new AreaDimension(startX, startZ, xSize, zSize));
        final Biome[] biomes = new Biome[xSize * zSize];
        for (int z = 0; z < zSize; ++z) {
            for (int x = 0; x < xSize; ++x) {
                biomes[x + z * xSize] = Biome.getBiome(area.func_202678_a(x, z), defaultBiome);
            }
        }
        return biomes;
    }
}
```

**Comment by kashike** [comment]
Please open separate issues for the remaining suggestions you have.

**Comment by Runemoro** [comment]
https://github.com/MinecraftForge/MCPConfig/issues/20
