### ISSUE TITLE
[Request] Automatically apply MCP mappings.

### ISSUE THREAD

**Issue by ahmed605** [MinecraftForge/MCPConfig#23]
**Please make MCPConfig apply MCP mappings automatically after decompiling.**

**Comment by xfl03** [comment]
Take 1.13.1 for instance.
Use command `.\gradlew :1.13.1:fernflowerClient` and wait.
Go to `.\build\versions\1.13.1\`, you can find `1.13.1.client.decomp.jar`.
It is decompiled and mapped.
