### ISSUE TITLE
Fernflower, Mergetool and Renametool don't apply jvmargs

### ISSUE THREAD

**Issue by Marcono1234** [MinecraftForge/MCPConfig#24]
The following `jar`s allow specifying `jvmargs` in the `config.json` file, but do not apply them when running the task. Especially for fernflower this might be rather important.
- [Fernflower](https://github.com/MinecraftForge/MCPConfig/blob/master/build.gradle#L158)
- [Mergetool](https://github.com/MinecraftForge/MCPConfig/blob/master/build.gradle#L169)
- [Renametool](https://github.com/MinecraftForge/MCPConfig/blob/master/build.gradle#L181)

This could probably be solved by adding `jvmArgs <config>.jvmargs` to the respective taks, for example

    task renameClient(type: RemapJar, dependsOn: [downloadRenameTool, downloadLibraries, filterClient]) {
        jar downloadRenameTool.dest
        // Use jvmargs
        jvmArgs RENAMETOOL.jvmargs
        input filterClient.archivePath
        mappings file(PATH_VERSION + 'joined.tsrg')
        args RENAMETOOL.args
        dest file(PATH_CACHED_VERSION + project.version + '.client.mapped.jar')
    }

**Comment by kashike** [comment]
Pull request?

**Comment by kashike** [comment]
#26
