### ISSUE TITLE
ExtractInheritance Gradle task annotations might be ignored

### ISSUE THREAD

**Issue by Marcono1234** [MinecraftForge/MCPConfig#27]
According to the Gradle documentation of the annotations [`InputFile`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputFile.html) and [`OutputFile`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/OutputFile.html) the annotations used for the [`ExtractInheritance`](https://github.com/MinecraftForge/MCPConfig/blob/master/buildSrc/src/main/java/net/minecraftforge/lex/ExtractInheritance.java) task might be ignored:
> This annotation should be attached to the getter method in Java or the property in Groovy. Annotations on setters or just the field in Java are ignored.

Therefore the annotations for the fields `input` and `dest` should probably be moved to the respective getters instead.

However, I am not that familiar with Gradle and since version 4.8.1 is used and the docs are for 4.10.2, I am not sure if this really applies. Therefore it would be good if someone with more experience could confirm and change it if necessary.

**Comment by LexManos** [comment]
Yes, I noticed that while working on FG. Either it never worked, or changed since Abrar wrote the classes I was working off as a reference. This should be fixed.. eventually..
