### ISSUE TITLE
Support for CSV mapping files

### ISSUE THREAD

**Issue by Marcono1234** [MinecraftForge/MCPConfig#29]
Since there is currently no support for CSV mapping files I created the project [removed]. The `README` file should hopefully explain it a little bit (might not display correctly at the moment because Github has some [issues](https://status.github.com/messages)).

Let me know if there is interest in using the project or parts of it for MCPConfig.

**Comment by jamierocks** [comment]
That's not what MCPConfig is for though... See https://github.com/MinecraftForge/MCPConfig/issues/23#issuecomment-426359506

**Comment by Marcono1234** [comment]
Isn't this tool partially a replacement for MCP? And what should you do otherwise to apply the CSV mappings?

**Comment by 0-x-2-2** [comment]
False

**Comment by jamierocks** [comment]
How in the world you took somewhat opening up the SRG files to being replacing MCP I don't know. How about use the same tools that have been used since forever? (SpecialSource, though eventually I'd like to see that replaced :p)

**Comment by LexManos** [comment]
MCPConfig is EXPLICITLY designed to NOT be a replacement for MCP.
MCP as a toolsuite is dead. We are in a era of Minecraft modding where direct base edits to the decompiled code, and redistribution of modified class files is a thing of the past.
Forge, LiteLoader, LaunchWrapper, there are many many tools that are out there for modifying the base game without having to create jar mods.

Please respect my wishes and don't do this. And to that end, I will not allow you to promote you doing it in this repo so i have removed your link.

**Comment by Marcono1234** [comment]
I am sorry. It was not my goal to reenable modifying the base game jar. I was rather looking for a tool which is able to decompile Minecraft and apply mappings so I can look at the code (for Mojira), and MCPConfig looked well suited for this task because you did a great job at providing the latest SRG / TSRG mappings and it sets up settings for the IDE.

I know that there are other tools, for example SpecialSource (as mentioned by @jamierocks), which however is not able to insert documentation, or ForgeGradle 3.0, but I am not sure if this can solve my problem. Apparently there is also [Srg2Source](https://github.com/MinecraftForge/Srg2Source) but it looks like it does not support insertion of documentation either.

Additionally, is there a place where you can get the latest SRG mappings? MCPConfig is more than that and is not as easy to query as a JSON file listing the existing mappings (similar to how it is done for the CSV mappings). [Forge maven](https://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2-srg.zip) had the SRG mappings for previous versions, but apparently 1.12.2 is the latest.
Do you create the SRG mappings by hand or is there a program which helps you with that?

Sorry if this got too off-topic.

**Comment by jamierocks** [comment]
Firstly, the documentation provided by MCP *isn't very good anymore* - its largely the same as its been for a number of releases, and therefor the reliability of it isn't so great anymore (Mojang obviously change stuff).

> Additionally, is there a place where you can get the latest SRG mappings? 

You kinda seem to contradict yourself - earlier on saying "you did a great job at providing the latest SRG / TSRG mappings". I'm not sure what you mean by this.

> Do you create the SRG mappings by hand or is there a program which helps you with that?

No, well mostly no - only class names are done by name. The SRG mappings are generated by [retroguard](https://github.com/ModCoderPack/Retroguard) (pending a replacement). They are updated version-to-version by a proprietary tool (again pending a replacement).

> Sorry if this got too off-topic.

I think it has :p

**Comment by jamierocks** [comment]
> The mappings are still actively maintained

I'm well aware, *the mappings* aren't what I was referring to - the javadocs were.

> Are they provided on Forge Maven together with a JSON file which lists all versions like it is the case for the CSV mappings, or is this Github project the only source?

Lex'll have to answer that one, I know that it builds zips with the mappings within but I'm not sure if they're deployed anywhere.
