### ISSUE TITLE
Differentiate the two Material classes

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MCPConfig#49]
Having two classes called simply "`Material`" is a recipe for confusion. They should have different names:

- [ ] `net/minecraft/block/Material` -> `net/minecraft/block/PhysicsMaterial`
- [ ] `net/minecraft/client/renderer/model/Material` -> `net/minecraft/client/renderer/model/RenderMaterial`

**Comment by jamierocks** [comment]
`block/Material` should stay IMO, 👍 to `RenderMaterial` though.
