### ISSUE TITLE
Could not apply Patches -> Build failed

### ISSUE THREAD

**Issue by Finnlife** [MinecraftForge/MCPConfig#52]
When i start "gradlew :1.14.4:projectClientApplyPatches" there is an Error.

http://prntscr.com/r08rhe

**Comment by DaemonUmbra** [comment]
Is there anything above this that explains the error in more detail?

**Comment by Finnlife** [comment]
No, in the screenshot is the whole Console.
I cant see more Errors.
But when i try other Decompilers there are Errors too.
In another Decompiler the Error was, that i cant run a Java VM above -Xmx1G because it only starts in 32 Bit.
Maby thats the Error?

**Comment by DaemonUmbra** [comment]
I believe Decomp is set to use 3G by default, so if 32-Bit is incapable of that the process may fail/
The solution would be to make sure you're using a 64 Bit JDK and not 32.

**Comment by Finnlife** [comment]
I have the 64-Bit version istalled. But the VM that im using (the decompiler) only uses 32 Bit...
http://prntscr.com/r0tn1e

**Comment by DaemonUmbra** [comment]
Where is JAVA_HOME pointing?

**Comment by Finnlife** [comment]
My JAVA_HOME is pointing to "C:\Program Files\Amazon Corretto\jdk1.8.0_242".

**Comment by DaemonUmbra** [comment]
Wait, are you trying to make a custom client?

**Comment by Finnlife** [comment]
Yes, i try do do a custom Client.

**Comment by DaemonUmbra** [comment]
Don't. This discussion is over
