### ISSUE TITLE
Particle.onGround decompiled incorrectly

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MCPConfig#56]
See https://github.com/MinecraftForge/MinecraftForge/issues/6595
It seems like 1.14.4 still had the patch: https://github.com/MinecraftForge/MCPConfig/blob/master/versions/release/1.14.4/patches/client/net/minecraft/client/particle/Particle.java.patch
But it got lost during the update to 1.15, most likely as the method changed and now requires an additional fix (the new collidedY check)

**Comment by LexManos** [comment]
Thought we fixed this in Fernflower.. Either way it should be fixed on that end but I can patch it in.
