### ISSUE TITLE
AbstractGUI -> GUIObject

### ISSUE THREAD

**Issue by Cyborgmas** [MinecraftForge/MCPConfig#57]
Widgets inherit from AbstractGUI, but I would not consider them an actual GUI. GUIObject seems more encompassing and a bit clearer. At first, I thought only Screens and such inherited from AbstractGUI, since they are GUIs.

**Comment by williewillus** [comment]
Perhaps AbstractGui is a bad name, but "GUIObject" is certainly much worse.

**Comment by Sm0keySa1m0n** [comment]
I would class a widget (buttons, scroll bars, lists etc.) as a graphical user interface and therefore I wouldn’t say AbstractGui is too bad of a name. It really doesn’t make a world’s difference either. It’s closely related enough and as far as I’m aware nobody is confused as to why a widget would extend `AbstractGui`...

**Comment by Cyborgmas** [comment]
So i saw it as:
a Screen is a GUIObject
a Widget is a GUIObject
 worked better than saying 
a Screen is an AbstractGUI  
a Widget is an AbstractGUI

But i decided to not be lazy and check all the overrids and some are indeed just GUIs... which makes a lot less sense .... anyways,  I tried :D
