### ISSUE TITLE
net.minecraft.client.particle.UnderwaterParticle -> AmbientParticle

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MCPConfig#61]
It's now used for underwater bubbles, crimson spores, and warped spores.

**Comment by LexManos** [comment]
BubbleParticle is already claimed.

**Comment by alcatrazEscapee** [comment]
Totally failed to do this in time for 1.16, but hey:

Here are the particles
![2020-06-26_17 22 17](https://user-images.githubusercontent.com/35673674/85902279-a86d3a80-b7d1-11ea-9b97-17dc45d356c0.png)
(the water one is there it just doesn't move)

They're all single pixels, and just spawn in specific areas. Could do something like `PixelParticle` (because that's actually what they are), but imo `AmbientParticle` better describes what they actually do (and as far as I can tell, isn't claimed anywhere).
