### ISSUE TITLE
TODO: Remove obf from ids and persist unique class IDs

### ISSUE THREAD

**Issue by LexManos** [MinecraftForge/MCPConfig#85]
SRG names historically have been `func_####_obf` or `field_###_obf` But the obf name is just the first time things have been encountered, and thus completely useless after a MC update. It gets into issues when people assume that this obf name means something, or that it can't change between MC versions.
So we should remove them.
This needs a bit of a script/tool chain change so i'm making this as a reminder/TODO.

Also, Orion has expressed interest in trying to track class name changes. Which can be done via our changelog but people have requested a pragmatic way. So we need to think of a way to persist unique IDs per class. Probably not something that should ship in MCPConfig itself, but stored in this repo for reference only.

**Comment by AutogolazzoJr** [comment]
I know there's supposed to be "no hand holding", but why are SRG methods and fields still used? Why not go directly from Minecraft to MCP methods using the mappings provided by mojang?

**Comment by covers1624** [comment]
Because we cant use them, and srg names gives us cross version support incase of mojang refactoring names

**Comment by gigaherz** [comment]
Because that would require storing the official names as a lookup mechanism, which would violate the license of the official names.
While the matching process can use the official names and just generate obf->mcp, as a result, what this issue is mentioning is specifically to store an intermediate name that is stable across both obf changes, and class renames, and the official names **cannot** be this intermediate.

**Comment by LexManos** [comment]
We've decided to go with a somewhat side stepping way to use the official names without distributing the official names.
It requires a bit more complex build system, but it works.
It also assigns unique ids to every class name and other un-srg-named entries. So it solves the issue of ids for things like enums/interface overrides.
Either way, we're moving forward with this system to hopefully be a bit more cohesive with others who want to use it.
