### ISSUE TITLE
Gradlew assemble failed

### ISSUE THREAD

**Issue by ppDotDLL** [MinecraftForge/MCPConfig#87]
A problem with task fixAccessLevels

Execution failed for task ':1.13.2:fixAccessLevels'.
> No signature of method: net.minecraftforge.srgutils.MappingFile.class() is applicable for argument types: (String) values: [dgh]
  Possible solutions: getClass(java.lang.String), getClass(), chain(net.minecraftforge.srgutils.IMappingFile), wait(), any(), equals(java.lang.Object)

**Comment by FinnT730** [comment]
Read the readme file, there is no hand holding.
Also, why for 1.13.2?? Why not for 1.15.2 or 1.16 pre releases??

**Comment by ppDotDLL** [comment]
oh ok. got it. sorry
