### ISSUE TITLE
net.minecraft.world.Blockreader -> net.minecraft.world.FixedBlockReader

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MCPConfig#98]
Missing upper camel case. It might be worth thinking renaming this to something like `FixedBlockReader`, since it only gives out `BlockState`s according to a `final` array.

**Comment by HellFirePvP** [comment]
It looks to be more like only reading a Y-column of a x/z position. As the input BlockState-array is interpreted as such.

![image](https://user-images.githubusercontent.com/7419378/89727019-75010b00-da21-11ea-986a-96a60c91974d.png)

So i'm not sure "BlockReader" itself might be a fitting naming as it'd suggest a generic implementation of IBlockReader which it definitely is not.

**Comment by sciwhiz12** [comment]
I opened the issue as `BlockReader` because I just corrected the name to use PascalCase/UpperCamelCase. I agree that it should be renamed to better fit how it works; and my suggestion is `FixedBlockReader`, since it gives `BlockState`s according to a fixed, `final` array. Should I rename the issue?
